import DashboardLayout from '../../../components/Layout/DashboardLayout';
import { useDemoData } from '../../../context/DemoDataContext';

export default function RecordsPage() {
  const { testResults, prescriptions, documents, markTestRead } = useDemoData();

  // Generate and download a text report for a test result
  const downloadTestReport = (test: typeof testResults[0]) => {
    const content = [
      '═══════════════════════════════════════════════════════',
      '              NEXUS HEALTH MEDICAL CENTER',
      '                   LAB REPORT',
      '═══════════════════════════════════════════════════════',
      '',
      `Test Name:      ${test.testName}`,
      `Date:           ${test.date}`,
      `Ordered By:     ${test.doctor}`,
      `Status:         ${test.status.toUpperCase()}`,
      '',
      '───────────────────────────────────────────────────────',
      'RESULTS SUMMARY',
      '───────────────────────────────────────────────────────',
      '',
      test.summary,
      '',
      '───────────────────────────────────────────────────────',
      'PATIENT INFORMATION',
      '───────────────────────────────────────────────────────',
      '',
      'Patient:        John Doe',
      'Patient ID:     NX-8421',
      'DOB:            Jan 15, 1985',
      '',
      '───────────────────────────────────────────────────────',
      '',
      'This report was generated by Nexus Health EHR System.',
      'For questions, contact your healthcare provider.',
      '',
      '═══════════════════════════════════════════════════════',
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${test.testName.replace(/[^a-zA-Z0-9]/g, '_')}_Report.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Generate and download a prescription summary
  const downloadPrescriptionReport = () => {
    const lines = [
      '═══════════════════════════════════════════════════════',
      '              NEXUS HEALTH MEDICAL CENTER',
      '            PRESCRIPTION SUMMARY REPORT',
      '═══════════════════════════════════════════════════════',
      '',
      'Patient:        John Doe',
      'Patient ID:     NX-8421',
      `Generated:      ${new Date().toLocaleDateString()}`,
      '',
      '───────────────────────────────────────────────────────',
      'ACTIVE PRESCRIPTIONS',
      '───────────────────────────────────────────────────────',
      '',
    ];

    prescriptions.forEach((rx, i) => {
      lines.push(`${i + 1}. ${rx.name} (${rx.dosage})`);
      lines.push(`   Frequency:    ${rx.frequency}`);
      lines.push(`   Prescribed:   ${rx.prescribedBy}`);
      lines.push(`   Period:       ${rx.startDate} — ${rx.endDate}`);
      lines.push(`   Refills Left: ${rx.refillsLeft}`);
      lines.push('');
    });

    lines.push('───────────────────────────────────────────────────────');
    lines.push('');
    lines.push('This report was generated by Nexus Health EHR System.');
    lines.push('═══════════════════════════════════════════════════════');

    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'Prescription_Summary.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Download a document (simulated)
  const downloadDocument = (docName: string) => {
    const content = [
      '═══════════════════════════════════════════════════════',
      '              NEXUS HEALTH MEDICAL CENTER',
      '               UPLOADED DOCUMENT',
      '═══════════════════════════════════════════════════════',
      '',
      `File Name:      ${docName}`,
      `Uploaded By:    John Doe (NX-8421)`,
      `Upload Date:    Oct 15, 2025`,
      '',
      '───────────────────────────────────────────────────────',
      '',
      'This is a simulated document download from the',
      'Nexus Health Electronic Health Records system.',
      '',
      'In a production environment, this would download',
      'the actual uploaded file from secure cloud storage.',
      '',
      '═══════════════════════════════════════════════════════',
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = docName.replace(/\.[^.]+$/, '') + '_download.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <DashboardLayout role="patient" title="Health Records">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-white mb-2">Health Records</h1>
        <p className="text-slate-400">View your lab results, prescriptions, and uploaded documents in one place.</p>
      </div>

      {/* Test Results */}
      <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-2">📄 Lab & Test Results</h2>
      <div className="space-y-3 mb-10">
        {testResults.map(test => (
          <div key={test.id} onClick={() => markTestRead(test.id)}
            className={`glass-card rounded-2xl p-6 cursor-pointer transition-all ${!test.read ? 'border-primary-500/30 bg-primary-500/5 hover:bg-primary-500/10' : 'hover:bg-white/[0.02]'}`}>
            <div className="flex justify-between items-start">
              <div className="flex-1">
                <h3 className="text-white font-semibold text-lg flex items-center gap-2">
                  {test.testName}
                  {!test.read && <span className="text-[10px] bg-primary-500/20 text-primary-400 px-2 py-0.5 rounded border border-primary-500/20">NEW</span>}
                </h3>
                <p className="text-sm text-slate-400 mt-1">{test.date} • Ordered by {test.doctor}</p>
                <p className="text-sm text-slate-300 mt-3 leading-relaxed">{test.summary}</p>
                <button onClick={(e) => { e.stopPropagation(); downloadTestReport(test); }}
                  className="mt-3 text-sm text-primary-400 hover:text-primary-300 transition-colors flex items-center gap-1.5 font-medium">
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                  Download Report
                </button>
              </div>
              <span className={`text-xs px-3 py-1.5 rounded-lg font-semibold shrink-0 ml-4 ${
                test.status === 'normal' ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/20' :
                test.status === 'abnormal' ? 'bg-amber-500/20 text-amber-400 border border-amber-500/20' :
                'bg-slate-500/20 text-slate-400 border border-slate-500/20'
              }`}>
                {test.status.toUpperCase()}
              </span>
            </div>
          </div>
        ))}
      </div>

      {/* Prescriptions */}
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-xl font-bold text-white flex items-center gap-2">💊 Prescriptions</h2>
        <button onClick={downloadPrescriptionReport}
          className="text-sm text-primary-400 hover:text-primary-300 transition-colors flex items-center gap-1.5 font-medium">
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
          Download All
        </button>
      </div>
      <div className="glass-card rounded-2xl overflow-hidden mb-10">
        <table className="w-full text-left">
          <thead>
            <tr className="border-b border-white/10 text-sm text-slate-400">
              <th className="p-4 font-semibold">Medication</th>
              <th className="p-4 font-semibold">Dosage</th>
              <th className="p-4 font-semibold hidden sm:table-cell">Frequency</th>
              <th className="p-4 font-semibold hidden md:table-cell">Prescribed By</th>
              <th className="p-4 font-semibold text-right">Refills</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-white/5 text-sm">
            {prescriptions.map(rx => (
              <tr key={rx.id} className="hover:bg-white/[0.02] transition-colors">
                <td className="p-4 text-white font-medium">{rx.name}</td>
                <td className="p-4 text-slate-300">{rx.dosage}</td>
                <td className="p-4 text-slate-400 hidden sm:table-cell">{rx.frequency}</td>
                <td className="p-4 text-slate-400 hidden md:table-cell">{rx.prescribedBy}</td>
                <td className="p-4 text-right">
                  <span className={`px-2 py-1 rounded text-xs font-semibold ${rx.refillsLeft > 2 ? 'bg-emerald-500/20 text-emerald-400' : rx.refillsLeft > 0 ? 'bg-amber-500/20 text-amber-400' : 'bg-red-500/20 text-red-400'}`}>
                    {rx.refillsLeft} left
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Documents */}
      <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-2">📁 Uploaded Documents</h2>
      <div className="glass-card rounded-2xl p-6">
        <div className="space-y-2">
          {documents.map((doc, i) => (
            <div key={i} className="flex items-center justify-between p-3 bg-white/5 rounded-xl border border-white/5 hover:bg-white/10 transition-colors">
              <div className="flex items-center gap-3">
                <span className="text-lg">📎</span>
                <span className="text-white font-medium">{doc}</span>
              </div>
              <button onClick={() => downloadDocument(doc)} className="text-primary-400 text-sm hover:text-primary-300 transition-colors flex items-center gap-1.5 font-medium">
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                Download
              </button>
            </div>
          ))}
        </div>
      </div>
    </DashboardLayout>
  )
}