-- Initial Database Schema for HMS (PostgreSQL)

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL, -- PATIENT, DOCTOR, ADMIN
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    dob DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS doctors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    specialty VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
    doctor_id BIGINT REFERENCES doctors(id) ON DELETE SET NULL,
    appointment_time TIMESTAMP NOT NULL,
    status VARCHAR(50) DEFAULT 'SCHEDULED', -- SCHEDULED, COMPLETED, CANCELLED
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS patient_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
    doctor_id BIGINT REFERENCES doctors(id) ON DELETE SET NULL,
    appointment_id BIGINT REFERENCES appointments(id) ON DELETE SET NULL,
    symptoms TEXT,
    predicted_disease VARCHAR(200),
    ai_scribe_transcript TEXT,
    doctor_notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS medications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
    doctor_id BIGINT REFERENCES doctors(id) ON DELETE SET NULL,
    medicine_name VARCHAR(255) NOT NULL,
    dosage VARCHAR(100),
    schedule_times TEXT, -- Comma-separated (e.g., "08:00,14:00,21:00")
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    instructions TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS medication_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medication_id BIGINT REFERENCES medications(id) ON DELETE CASCADE,
    scheduled_time TIMESTAMP NOT NULL,
    taken_time TIMESTAMP,
    status VARCHAR(50) DEFAULT 'PENDING', -- PENDING, TAKEN, MISSED
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- MULTI-HOSPITAL MEDICINE SHARING SYSTEM TABLES

CREATE TABLE IF NOT EXISTS hospitals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Link users to their specific hospital
ALTER TABLE users ADD COLUMN IF NOT EXISTS hospital_id BIGINT REFERENCES hospitals(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS medicine_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id BIGINT REFERENCES hospitals(id) ON DELETE CASCADE,
    medicine_name VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 0,
    expiry_date DATE NOT NULL,
    status VARCHAR(50) DEFAULT 'AVAILABLE', -- AVAILABLE, EXPIRING, SHARED, TRANSFERRED
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transfer_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_hospital_id BIGINT REFERENCES hospitals(id) ON DELETE CASCADE,
    to_hospital_id BIGINT REFERENCES hospitals(id) ON DELETE CASCADE,
    medicine_id BIGINT REFERENCES medicine_inventory(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL,
    status VARCHAR(50) DEFAULT 'PENDING', -- PENDING, APPROVED, REJECTED, COMPLETED
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- SOS EMERGENCY AMBULANCE SYSTEM TABLES

CREATE TABLE IF NOT EXISTS ambulances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id BIGINT REFERENCES hospitals(id) ON DELETE CASCADE,
    driver_name VARCHAR(100) NOT NULL,
    driver_phone VARCHAR(20) NOT NULL,
    current_latitude DOUBLE PRECISION,
    current_longitude DOUBLE PRECISION,
    status VARCHAR(50) DEFAULT 'AVAILABLE', -- AVAILABLE, BUSY
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sos_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    hospital_id BIGINT REFERENCES hospitals(id) ON DELETE SET NULL,
    ambulance_id BIGINT REFERENCES ambulances(id) ON DELETE SET NULL,
    status VARCHAR(50) DEFAULT 'PENDING', -- PENDING, DISPATCHED, ARRIVED, COMPLETED
    emergency_type VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Add emergency contact to patients
ALTER TABLE patients ADD COLUMN IF NOT EXISTS emergency_contact_name VARCHAR(200);
ALTER TABLE patients ADD COLUMN IF NOT EXISTS emergency_contact_phone VARCHAR(20);

-- Insert demo ambulances
-- INSERT INTO ambulances (hospital_id, driver_name, driver_phone, current_latitude, current_longitude, status) VALUES 
-- (1, 'John Driver', '+1-555-0101', 40.7128, -74.0060, 'AVAILABLE'),
-- (1, 'Mike Speed', '+1-555-0102', 40.7150, -74.0010, 'AVAILABLE'),
-- (2, 'Sarah Swift', '+1-555-0103', 40.7306, -73.9352, 'AVAILABLE'),
-- (4, 'Alex Rescue', '+1-555-0104', 40.7831, -73.9712, 'AVAILABLE');

-- SMART SUGGESTION SYSTEM UPDATES

-- Update hospitals with capacity and location data
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS emergency_available BOOLEAN DEFAULT FALSE;
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS beds_available INTEGER DEFAULT 0;
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

-- Update doctors with ratings, experience, and verification data
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS hospital_id BIGINT REFERENCES hospitals(id) ON DELETE SET NULL;
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS rating DECIMAL(3, 2) DEFAULT 5.0;
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS experience_years INTEGER DEFAULT 0;
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS available BOOLEAN DEFAULT TRUE;
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS license_number VARCHAR(100);
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS qualification VARCHAR(255);

CREATE TABLE IF NOT EXISTS doctor_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id BIGINT REFERENCES doctors(id) ON DELETE CASCADE,
    doc_type VARCHAR(50) NOT NULL, -- LICENSE, DEGREE, ID_PROOF
    file_path VARCHAR(255) NOT NULL,
    status VARCHAR(50) DEFAULT 'PENDING', -- PENDING, APPROVED, REJECTED
    admin_notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id VARCHAR(50) NOT NULL,
    receiver_id VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    type VARCHAR(20) NOT NULL DEFAULT 'CHAT',
    is_read BOOLEAN DEFAULT FALSE,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert some dummy hospitals for testing
-- INSERT INTO hospitals (name, location, emergency_available, beds_available, latitude, longitude) VALUES 
-- ('Metro General Hospital', 'Downtown, City-Center', TRUE, 120, 40.7128, -74.0060),
-- ('City Childrens Hospital', 'Westside Plaza', TRUE, 45, 40.7306, -73.9352),
-- ('Apex Cardiology Center', 'East Avenue, Block-B', FALSE, 25, 40.7484, -73.9857),
-- ('Nexus Health Central', 'North Hills', TRUE, 85, 40.7831, -73.9712);
